### PR TITLE
String instead of InputFile, refactor get_type #6

### PR DESCRIPTION
**Pull request by 7flash**

### CODE REVIEW

**Comment by 7flash** [comment]
This PR includes two changes:

First, **get_type_without_optional** is removed and  **check_optional** replaced with **with_optional**

Second, InputFile type replaced with String to resolve the issue #6

**Comment by 7flash** [comment]
image
https://core.telegram.org/bots/api#inputfile

As per documentation, InputField contains no fields that can be passed as arguments in method, and instead should be handled separately, perhaps allowing to read files from file system and uploading through API as multipart (but not as other fields in the request)

image

**Comment by 7flash** [comment]
The proposed change solves the issue #6 by allowing to pass URL in the arguments to functions: sendPhoto, sendSticker, setWebhook, sendAudio, sendVideo, sendVoice, snedSticker, sendDocument, sendAnimation, sendVideoNote

**Comment by 7flash** [comment]
Testing branch: https://github.com/7flash/ferrisgram/tree/7flash/second-testing-sendphoto

```
# generate types from local API file
cd generator
cargo run
# compile a script which using sendPhoto function
cd ..
cargo run --bin echobot
```

**Comment by 7flash** [comment]
@anonyindian

**Comment by celestix** [comment]
Hey @7flash, Thanks for the PR! As far as now, It looks good to me but for a better assurance, please generate the codes again with respect to this PR so that the changes in the main code are visible as well.

The PR will be merged once the generated output is ready and we can review it further,
Thank You!

**Comment by 7flash** [comment]
It has regenerated all the types but with differences in formatting styles. Idk if that's a problem and perhaps formatting could be enforced through some linter? Also I can regenerate only those types which are affected based on testing branch (reading API from local file)

**Review by celestix — APPROVED** [review]

**Pull request merged**
